SOURCES		= color_temperature.c
#HEADERS		= color_temperature.h
OBJS		= color_temperature.c.o
PROGRAMS	= color_temperature.exe

color_temperature.exe: color_temperature.c.o

color_temperature.c.o: color_temperature.c color_temperature.h

all: $(PROGRAMS)
